version: '3'

services:
  dynamodb-local-testing:
    image: amazon/dynamodb-local:1.20.0
    container_name: dynamodb-local-testing
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=wt20ei
      - AWS_SECRET_ACCESS_KEY=9t246v
      - AWS_DEFAULT_REGION=localhost
